dist: xenial
services:
  - mysql
language: php
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: TODO
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
php:
- 7.1
- 7.2
- nightly
env:
- WP_VERSION=latest WP_MULTISITE=1 TRAVIS_NODE_VERSION="8"
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
install:
- node -v
- npm install
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- git clone --depth=1 https://github.com/pressbooks/pressbooks.git ../pressbooks
- cd ../pressbooks && composer install --no-dev
- cd ../pressbooks-saml-sso
script:
- npm run lint
- npm run build:production
- vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml *.php inc/ bin/
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MWygLxWT7f+DKBMSbzHmVrZ42yD/IIwhOfngTUaLoLeIJ3ImhhmBkpXYZhmNF6HNT4R0cIeyNufDdbcQ/8S2D0paJot0DRRH4fwU8o3CSpMbdvEH3C6jLjJM60l+FaStXGQ5TFFvl2qu1WF8/d6Mvzr+pqNlqudSbFCrex6BOFrxwf0XqSpU6euO6RtLMMgBWWKTtVMU3SM9uRbpwrihwUhtlUuROXZjPW5sl2iWIcbl00a3p6YvCLDGW4j3CplXPhEGVr03fCCDIBsal6rPL9/K6gC74y4tAE5xH2xEIWD781kmGtyXBzvQDGxeGr6L5DH6ZBN52qaWMiLlJWpX7t4pPGIE5w78MV6WnmmVu96qij0josux+QZWavQ9KQwCmaq06QdR2rqpXa2jHJPGYrQbgFKhOWi4Z4T3eWUt3I+Euaw3KEB8Vf4Vix05goWkt9JKqHn6UdRI6J3RCnBG7NM5HPhMyFTGgInppm4m5RiVb/PaKAmkpy4MbKIxsG5FvfLimlyQdaXs62YYLyuHUaGcepPnDux6j9zh1ZHQROB3CmBPIDRJZje2htVkm4ikGmzsE9+YnI1lkFUZuN6lh5yUoyAeDIr9JB/GH5U9PSjJQz3YECXbFXMshYwEPpGE5EzBtqRdG9PchyOqj0sQ79NlQRhijBsn6itrP+u0jc8=
  file: "pressbooks-saml-sso-$TRAVIS_TAG.zip"
  on:
    tags: true
    repo: pressbooks/pressbooks-saml-sso
