name: Update POT file

on:
  push:
    branches:
    - dev
    paths:
    - '**.php'
    - '**.js'
  workflow_dispatch:

jobs:
  update-pot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer
    - name: Install WP CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar
        chmod +x wp-cli-nightly.phar
        sudo mv wp-cli-nightly.phar /usr/local/bin/wp
        wp package install wp-cli/i18n-command
    - name: Update POT file
      run: wp i18n make-pot . languages/pressbooks-saml-sso.pot --domain=pressbooks-saml-sso --slug=pressbooks-saml-sso --package-name="Pressbooks SAML SSO" --headers="{\"Report-Msgid-Bugs-To\":\"https://github.com/pressbooks/pressbooks-saml-sso/issues\"}"
    # Remove this step once you are satisfied with the results; alternatively, you can leave it in place and remove
    # the commented out step that follows.
    - name: Open PR with changes
      uses: peter-evans/create-pull-request@v4
      with:
        title: 'chore(l10n): update languages/pressbooks-saml-sso.pot'
    # - name: Commit updated POT file
    #   uses: stefanzweifel/git-auto-commit-action@v4.13.1
    #   with:
    #     commit_message: 'chore(l10n): update languages/pressbooks-saml-sso.pot'
    #     file_pattern: '*.pot'
