name: Update POT file

on:
  push:
    branches:
    - dev
    paths:
    - '**.php'
    - '**.js'

jobs:
  update-pot:
    runs-on: ubuntu-latest
    if: github.repository == "pressbooks/pressbooks-saml-sso" # Don't run on forks.
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        tools: composer, wp-cli
    - name: Install dependencies
      run: |
        wp package install wp-cli/i18n-command:2.2.6
        wp package install pressbooks/pb-cli:dev-dev#800cec8
        composer require jenssegers/blade:1.1.0
    - name: Update POT file
      run: wp pb make-pot . languages/pressbooks-saml-sso.pot --require=vendor/autoload.php --domain=pressbooks-saml-sso --slug=pressbooks-saml-sso --package-name="Pressbooks SAML SSO" --headers="{\"Report-Msgid-Bugs-To\":\"https://github.com/pressbooks/pressbooks-saml-sso/issues\"}"
    # Remove the next four lines and uncomment the last five lines once the process has been confirmed to work as desired.
    - uses: actions/upload-artifact@v2
      with:
        name: pressbooks-saml-sso.pot
        path: languages/pressbooks-saml-sso.pot
    # - name: Commit updated POT file
    #   uses: stefanzweifel/git-auto-commit-action@v4.1.1
    #   with:
    #     commit_message: 'chore(l10n): update languages/pressbooks-saml-sso.pot'
    #     file_pattern: '*.pot'
