name: Update POT file

on:
  push:
    branches:
    - dev
    paths:
    - '**.php'
    - '**.js'
  workflow_dispatch:

jobs:
  update-pot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, wp-cli/wp-cli-bundle
    - name: Update POT file
      run: wp i18n make-pot . languages/pressbooks-saml-sso.pot --domain=pressbooks-saml-sso --slug=pressbooks-saml-sso --package-name="Pressbooks SAML2 Single Sign-On" --headers="{\"Report-Msgid-Bugs-To\":\"https://github.com/pressbooks/pressbooks-saml-sso/issues\"}"
    - name: Commit updated POT file
      uses: stefanzweifel/git-auto-commit-action@v4.13.1
      with:
        commit_message: 'chore(l10n): update languages/pressbooks-saml-sso.pot'
        file_pattern: '*.pot'